# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:
  label:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write

    steps:
#    - uses: actions/labeler@v4
#      with:
#        repo-token: "${{ secrets.ACTIONS_TOKEN }}"

    - name: Set up Maven
      uses: wkdehdlr/setup-maven@v4.4.1
      with:
        maven-version: 3.6.3

#      - name: Setup Maven Action
#        uses: s4u/maven-settings-action@v2.6.0
#
      - run: mvn -v